

export const data =[
  { id:'HT2', 
  propertyname:"Ambience Tiverton ",
  img:"https://i.ibb.co/JthY4Zf/Ambience-Tirevton-01.webp",
  address1:"Sector 50, Noida",
  address2:"F-33, F Block, Sector 50, Noida",
  price:"10,600",
  RERANO:"UPRERAPRJ4249",
  PropertyID:"HZ29",
  LaunchDate:"October 2014",
  projectarea:"4 Acres",
  Sizes:"2548 - 6055 Sq.ft.",
  PossessionDate:"March, 2020",
  TotalTowers:"7 Towers",
  TotalFloors:"26 Floors",
  ProjectStatus:"Ready To Move",
  PropertyType:"Residential",
  Configurations:"3 BHK, 4 BHK ,5 BHK",
  location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.7506412924913!2d77.36810131549448!3d28.577249693330682!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5b84c2b5a73%3A0xaf840e835cff6c27!2sAmbience%20Tiverton!5e0!3m2!1sen!2sin!4v1674031553468!5m2!1sen!2sin" ,
  ConstructionType: "",
  TotalFlats:"284",
  GreenArea:"70%",
  TotalFloors:"25",
  Ceilingheight:"10 Ft.",
  MainDoorHeight:"9 Ft.",
  InternalDoorHeight:"7 Ft.",
  text:"Ambience Tiverton is a luxury residential project located in Sector 50, Noida, India. The project is developed by Ambience Group, a renowned real estate developer known for its premium projects across India. Ambience Tiverton offers spacious apartments with modern amenities and facilities, making it an ideal choice for those looking for a comfortable and luxurious living experience.Features and Amenities:Ambience Tiverton offers 3-4 BHK apartments with spacious balconies, allowing residents to enjoy the panoramic views of the surroundings. The apartments are designed to provide maximum comfort and convenience to the residents. The project is equipped with a range of amenities and facilities such as a clubhouse, swimming pool, gym, sports facilities, and landscaped gardens. The project also features a multi-level car parking facility, 24x7 security, and power backup.Location and Connectivity:Ambience Tiverton is located in Sector 50, Noida, which is a prime residential area in the city. The location is well-connected to other parts of Noida, as well as Delhi and other NCR cities, via roads, highways, and metro. The project is in close proximity to major IT hubs and commercial centers, making it an ideal choice for working professionals.Design and Architecture:Ambience Tiverton boasts of a contemporary and elegant design, with modern architecture and interiors. The apartments are designed to maximize natural light and ventilation, providing a healthy living environment for the residents. The project has received several awards and recognitions for its design, architecture, and construction quality.Investment Potential:Ambience Tiverton is a premium residential project that offers a high-end living experience. The project is designed to cater to the needs of the urban elite, and the apartments are priced accordingly. The location of the project, along with the premium amenities and facilities, makes it a desirable investment option for those looking for a luxurious and comfortable living experience.In conclusion, Ambience Tiverton is a premium residential project that offers a luxurious living experience. With its modern amenities, prime location, and contemporary design, the project is an ideal choice for those looking for a comfortable and luxurious lifestyle.",
  text1:"Ambience Tiverton is a luxurious residential project located in Sector 50, Noida. It offers spacious 3 and 4 BHK apartments with modern amenities such as a swimming pool, gymnasium, clubhouse, and landscaped gardens. The apartments are equipped with state-of-the-art facilities such as modular kitchens with granite counters, imported marble flooring in living, dining, and bedrooms, and high-quality bathroom fittings. The project is conveniently located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. With its luxurious amenities and convenient location, Ambience Tiverton offers a comfortable living experience for those seeking a premium lifestyle in Noida."
},
{ id:'HT3', 
propertyname:"Godrej Woods",
img:"https://i.ibb.co/qY1CJZc/Godrej-Wood-01.webp",
price:"11,590 ",
address1:"Sector 43, Noida",
address2:"Block A, Sector 43, Noida, Uttar Pradesh 201303",
RERANO:"UPRERAPRJ704730",
status:"Ready to Move",
LaunchDate:"May 2017",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"11 Acres",
Sizes:"1255 - 3759 Sq.ft.",
ProjectUnits:"1100 Flats",
LaunchDate:"Jan, 2021",
TotalTowers:"10 Towers",
TotalFloors:"34 Floors",
Configurations:"2BHK, 3BHK, 4BHK, 5BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.3666738551206!2d77.34894121549411!3d28.558750094166488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5d5046eee85%3A0x9ed7749be19b1b56!2sGodrej%20Woods%2C%20Sector%2043%2C%20Noida!5e0!3m2!1sen!2sin!4v1674031636046!5m2!1sen!2sin",   
TotalFlats:"1245",
GreenArea:"70%",
TotalFloors:"34",
Ceilingheight:"10 Ft",
MainDoorHeight:"9 Ft.",
InternalDoorHeight:"7 Ft.",
text:"Godrej Woods is a residential project by Godrej Properties located in Sector 43, Noida. The project offers luxurious 2, 3, and 4 BHK apartments with world-class amenities such as a clubhouse, swimming pool, gymnasium, children's play area, and landscaped gardens. The apartments are spacious and well-designed, offering residents a comfortable living experience. The project also features 24/7 security and surveillance systems, ensuring the safety of residents.Godrej Woods is strategically located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. The project is also well-connected to other parts of the city via major highways and roads, making it an ideal choice for those who need to commute regularly.The project is built with a focus on sustainability and environmental responsibility, with features such as rainwater harvesting, solar power generation, and waste management systems. This makes it a great choice for those who are conscious about the environment and want to contribute to a greener future.Overall, Godrej Woods is a great choice for those seeking a luxurious and comfortable living experience in Noida, with world-class amenities, convenient location, and a focus on sustainability.",
text1:"Godrej Woods is a premium residential project located in Sector 43, Noida, offering luxurious 2, 3, and 4 BHK apartments with top-notch amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed with modern architecture and spacious interiors, providing a comfortable living experience. The project is strategically located with easy access to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Godrej Woods is a great choice for those looking for a premium living experience in Noida."

},
{ id:'HT12', 
propertyname:"Dasnac Burj Noida",
img:"https://i.ibb.co/8D9T5M7/Burj-01.webp",
price:"11,500",
address1:"Sector 75, Noida",
address2:"Sector 75, Noida",
RERANO:"UPRERAPRJ498423",
status:"Under Construction",
LaunchDate:"April 2019",
PossessionDate:"Ready to Move",
Projecttype:"Residential",
projectarea:"1 Acres",
Sizes:"2510.00 sq.ft. - 6300.00 sq.ft.",
ProjectUnits:"131 units",
PossessionDate:"Dec, 2023",
TotalTowers:"1",
Configurations:"3, 4, 5.5 BHK Apartment, Duplexes",
location:"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14015.233447054106!2d77.3819281!3d28.5755168!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef0bb7b93bd9%3A0x723ac9083147a601!2sDASNAC%20Burj%20Noida%20(Official)!5e0!3m2!1sen!2sin!4v1679295825659!5m2!1sen!2sin", 
TotalFlats:"131",
GreenArea:"80%",
TotalFloors:"35",
Ceilingheight:"10 ft.",
MainDoorHeight:"9 Ft.",
InternalDoorHeight:"7 Ft.",
text:"Dasnac Burj Noida is a luxurious residential project located in the prime location of Sector 75, Noida. The project offers 2, 3, and 4 BHK apartments with spacious and well-designed interiors. The apartments range in size from 1050 sq. ft. to 2375 sq. ft. and are available in various configurations to suit the needs of different homebuyers. The project features a range of modern amenities, including a swimming pool, gymnasium, yoga and meditation area, multipurpose hall, kids' play area, landscaped gardens, and more.One of the unique features of Dasnac Burj Noida is the concept of vertical gardens, which enhances the beauty of the project and provides a serene and tranquil environment for residents. The project also features smart home automation technology, allowing residents to control various aspects of their homes, including lighting, temperature, and security, through their smartphones.The location of Dasnac Burj Noida is another significant advantage, as it is well-connected to major roads and highways, making it easy for residents to travel to different parts of the city. The project is also in close proximity to various educational institutions, hospitals, shopping centers, and other essential amenities.Overall, Dasnac Burj Noida is an excellent residential project that offers a luxurious lifestyle to its residents with a range of modern amenities, unique features, and a prime location.",
text1:"Dasnac Burj Noida is a luxurious residential project located in the prime location of Sector 75, Noida. The project offers a wide range of spacious and beautifully designed apartments that are equipped with modern amenities to provide a comfortable lifestyle. The apartments are available in 3BHK and 4BHK configurations with sizes ranging from 1950 sq. ft. to 3450 sq. ft. The project boasts of world-class amenities such as a state-of-the-art clubhouse, swimming pool, landscaped gardens, children's play area, gymnasium, and many more. The project is strategically located with easy access to major highways and is in close proximity to reputed educational institutions, hospitals, shopping centers, and entertainment hubs, making it an ideal place to call home. With its luxurious amenities, prime location, and exquisite design, Dasnac Burj Noida is a perfect place for those looking to enjoy a sophisticated and comfortable lifestyle.",

},{ id:'HT15', 
propertyname:"Ivy County",
address1:"Sector 75",
address2:"Sector 75",
price:"10,500",
RERANO:"UPRERAPRJ757529",
status:"Under Construction",
LaunchDate:"May 2017",
Projecttype:"Residential",
projectarea:"5 Acres",
Sizes:"1656-2511 Sq.Ft.",
PossessionDate:"Sep 23",
TotalTowers:"5",
TotalFloors:"27",
Configurations:"3 BHK,4 BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin",
TotalFlats:"546",
GreenArea:"78%",
TotalFloors:"27",
Ceilingheight:"10 Ft.",
MainDoorHeight:"9 Ft",
InternalDoorHeight:"7 Ft.",
text:"Ivy County Noida is a premier residential development located in the bustling city of Noida in India. It is a luxury residential complex designed to offer a modern and comfortable living experience to its residents. For SEO purposes, here is a brief overview of Ivy County Noida:Location:Ivy County Noida is located in one of the most sought-after locations in Noida, with easy access to major highways, public transportation, and key commercial areas. It is in close proximity to schools, hospitals, shopping centers, and other important amenities.Architecture and Design:Ivy County Noida is designed to offer a luxurious living experience with modern amenities and state-of-the-art architecture. The complex features spacious and well-designed apartments with premium finishes and fittings.Amenities:Residents of Ivy County Noida can enjoy a range of modern amenities, including a swimming pool, gymnasium, landscaped gardens, clubhouse, and sports facilities. The complex also features 24/7 security and power backup for the convenience and safety of its residents.Investment Opportunities:Ivy County Noida offers excellent investment opportunities for those looking to invest in real estate in Noida. With its prime location, modern amenities, and attractive pricing, the complex is an ideal choice for investors and homebuyers alike.Overall, Ivy County Noida is a premier residential complex that offers a modern and luxurious living experience in the heart of Noida. Its prime location, modern amenities, and attractive pricing make it a great investment opportunity for those looking to invest in real estate in Noida.",
text1:"Ivy County Noida is a premium residential complex located in one of the most sought-after areas of Noida. The complex offers a luxurious living experience with modern amenities and state-of-the-art architecture. It is designed to cater to the needs and preferences of modern families, providing spacious and well-designed apartments with premium finishes and fittings.Residents of Ivy County Noida can enjoy a range of modern amenities, including a swimming pool, gymnasium, landscaped gardens, clubhouse, and sports facilities. It is a great opportunity to invest in the growing real estate market of Noida and secure a premium property in a prime location.Overall, Ivy County Noida is a premium residential complex that offers a modern and luxurious living experience in the heart of Noida. Its modern amenities, prime location, and investment potential make it an ideal choice for those looking for a comfortable and convenient living space or a smart investment opportunity. "

}
    ];
  
  