
let publicUrl = process.env.PUBLIC_URL + "/";

export const data =[
  { id:'HT1', 
  propertyname:"Ace Divino",
  img:publicUrl+"assets/img/banner/acedivino.webp",
  floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
  floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
  floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
  price:"74 Lakhs-2.7 Cr ",
  address1:"Greater Noida West",
  address2:"Plot No. GH 14A, Sector 1 Noida Extension, Greater Noida",
  RERANO:"UPRERAPRJ6734",
  launchDate:"May 2017",
  status:"Ready to Move",
  projectType:"Residential ",
  projectArea:"10.41 Acres",
  sizes:"995 - 1875 Sq.ft",
  launchDate:"May, 2017",
  possessionDate:"Dec, 2022",
  totalTowers:"11 Towers",
  totalFloors:"23 Floors",
  projectStatus:"Ready To Move",
  propertyType:"Residential",
  configurations:"2BHK, 3BHK, 4BHK",
  location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.2857262981247!2d77.43616551549425!3d28.561181594056546!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef70fc3a9861%3A0x9ff8321e65d81a96!2sAce%20Divino!5e0!3m2!1sen!2sin!4v1674031451895!5m2!1sen!2sin",
  constructionType: "Maven",
  totalFlats:"1550",
  greenArea:"78%",
  totalFloors:"22",
  loading:"30%",
  ceilingHeight:"10 Ft.",
  mainDoorHeight:"8 Ft",
  internalDoorHeight:"7 Ft.",
  para1:"Ace Divino is a premium residential project located in the bustling city of Noida, Uttar Pradesh. Developed by Ace Group, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"Spread over 10.5 acres of land, Ace Divino offers 2 BHK, 3 BHK, and 4 BHK apartments that range in size from 995 square feet to 2315 square feet. The apartments are spacious and well-ventilated, and they offer a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Ace Divino also offers a wide range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in the heart of Noida Extension, Ace Divino enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Ace Divino is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida.",
  text1:"Ace Divino is a residential project located in Greater Noida West, India. Developed by Ace Group, the project offers a range of apartments with modern amenities and facilities. The project features spacious and well-designed units with contemporary interiors and high-quality finishes. The development offers a host of recreational amenities such as a clubhouse, swimming pool, gymnasium, sports facilities, and landscaped gardens. Additionally, the project is well-connected to the major parts of the city and is situated in close proximity to various educational, commercial, and entertainment hubs. Ace Divino offers an ideal blend of comfort, luxury, and convenience, making it a desirable residential option for modern urban living."
  },
  { id:'HT2', 
    propertyname:"Ambience Tiverton ",
    img:publicUrl+"assets/img/banner/ambience.webp",
    floorPlan1:"https://i.imgur.com/Ax8PPjE.jpg",
    superarea1:"2548 Sq.Ft.",
    type1:"3 BHK",
    floorPlan2:"https://i.imgur.com/h5oDvgX.jpg",
    type2:"3 BHK",
    superarea2:"2548 Sq.Ft.",
    floorPlan3:"https://i.imgur.com/K7jqDdL.jpg",
    type3:"4 BHK",
    superarea3:"3284 Sq.Ft.",
    pic1:"https://i.imgur.com/cYjAvlj.jpg",
    pic2:"https://i.imgur.com/V6L4sY4.jpg",
    pic3:"https://i.imgur.com/R0qW6ta.jpg",
    siteplan:"https://is1-2.housingcdn.com/012c1500/30230216f14230c82b65c5175dd2949b/v0/fs-large.jpeg.webp",
    price:"2.7 Cr- 5 Cr ",
    address1:"Sector 50, Noida",
    address2:"F-33, F Block, Sector 50, Noida",
    RERANO:"UPRERAPRJ4249",
    launchDate:"October 2014",
    projectArea:"4 Acres",
    sizes:"2548 - 6055 Sq.ft.",
    possessionDate:"March, 2020",
    totalTowers:"7 Towers",
    totalFloors:"26 Floors",
    status:"Ready To Move",
    propertyType:"Residential",
    configurations:"3 BHK, 4 BHK ,5 BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.7506412924913!2d77.36810131549448!3d28.577249693330682!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5b84c2b5a73%3A0xaf840e835cff6c27!2sAmbience%20Tiverton!5e0!3m2!1sen!2sin!4v1674031553468!5m2!1sen!2sin" ,
    constructionType: "",
    totalFlats:"284",
    greenArea:"70%",
    totalFloors:"25",
    ceilingHeight:"10 Ft.",
    mainDoorHeight:"9 Ft.",
    internalDoorHeight:"7 Ft.",
   
    text1:"Ambience Tiverton is a luxurious residential project located in Sector 50, Noida. It offers spacious 3 and 4 BHK apartments with modern amenities such as a swimming pool, gymnasium, clubhouse, and landscaped gardens. The apartments are equipped with state-of-the-art facilities such as modular kitchens with granite counters, imported marble flooring in living, dining, and bedrooms, and high-quality bathroom fittings. The project is conveniently located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. With its luxurious amenities and convenient location, Ambience Tiverton offers a comfortable living experience for those seeking a premium lifestyle in Noida.",
    video:"https://www.youtube.com/embed/cOjNovruLV0" ,
    para1:"Ambience Tiverton Noida is a luxurious residential project located in the upscale locality of Sector 50 in Noida, India. Spread across 3.5 acres of prime land, the project comprises of 3 and 4 BHK apartments that offer a perfect blend of comfort, style, and convenience. The apartments range in size from 2548 sq. ft. to 3273 sq. ft., and the project features 3 towers with a total of 248 units.",
    para2:"The project offers a wide range of amenities and facilities, including a swimming pool, gymnasium, clubhouse, landscaped gardens, and more. The apartments feature premium finishes and fittings, such as imported marble flooring, modular kitchens with high-quality appliances, and air conditioning in all rooms. The project also features advanced security systems to ensure the safety of its residents.",
    para3:"The location of Ambience Tiverton Noida is another highlight, with easy access to major commercial hubs, educational institutions, and healthcare facilities in the city. The project is located close to several prestigious schools and colleges, making it an ideal choice for families with children. The location is also well-connected to major roads and highways, making it easy for residents to travel to other parts of the city.",
    para4:"The project has been designed keeping in mind the needs and preferences of the modern-day family. The apartments are spacious, well-ventilated, and offer ample natural light, providing a serene and peaceful living environment. The project also offers a range of amenities that cater to the needs of different age groups, making it an ideal choice for families with children, seniors, and young professionals.",
    para5:"In conclusion, Ambience Tiverton Noida is a premium residential project that offers a luxurious and comfortable lifestyle to its residents. With its world-class amenities, premium finishes, and convenient location, the project is an ideal choice for those seeking a premium residential property in Noida.",
  },
  { id:'HT3', 
    propertyname:"Godrej Woods",
    img:publicUrl+"assets/img/banner/woods.webp",
    floorPlan1:publicUrl+"assets/img/FloorPlan/woods/1.jpg",
    floorPlan2:publicUrl+"assets/img/FloorPlan/woods/2.jpg",
    floorPlan3:publicUrl+"assets/img/FloorPlan/woods/3.jpg",
    price:"1.64 Cr- 5.52 Cr ",
    projectArea:"4 Acres",
    address1:"Sector 43, Noida",
    address2:"Block A, Sector 43, Noida, Uttar Pradesh 201303",
    RERANO:"UPRERAPRJ704730",
    status:"Ready to Move",
    launchDate:"May 2017",
    possessionDate:"Ready to Move",
    projectType:"Residential",
    projectarea:"11 Acres",
    sizes:"1255 - 3759 Sq.ft.",
    projectUnits:"1100 Flats",
    launchDate:"Jan, 2021",
    totalTowers:"10 Towers",
    totalFloors:"34 Floors",
    configurations:"2BHK, 3BHK, 4BHK, 5BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.3666738551206!2d77.34894121549411!3d28.558750094166488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5d5046eee85%3A0x9ed7749be19b1b56!2sGodrej%20Woods%2C%20Sector%2043%2C%20Noida!5e0!3m2!1sen!2sin!4v1674031636046!5m2!1sen!2sin",   
    totalFlats:"1245",
    greenArea:"70%",
    totalFloors:"34",
    ceilingHeight:"10 Ft",
    mainDoorHeight:"9 Ft.",
    internalDoorHeight:"7 Ft.",
    text:"Godrej Woods is a residential project by Godrej Properties located in Sector 43, Noida. The project offers luxurious 2, 3, and 4 BHK apartments with world-class amenities such as a clubhouse, swimming pool, gymnasium, children's play area, and landscaped gardens. The apartments are spacious and well-designed, offering residents a comfortable living experience. The project also features 24/7 security and surveillance systems, ensuring the safety of residents.Godrej Woods is strategically located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. The project is also well-connected to other parts of the city via major highways and roads, making it an ideal choice for those who need to commute regularly.The project is built with a focus on sustainability and environmental responsibility, with features such as rainwater harvesting, solar power generation, and waste management systems. This makes it a great choice for those who are conscious about the environment and want to contribute to a greener future.Overall, Godrej Woods is a great choice for those seeking a luxurious and comfortable living experience in Noida, with world-class amenities, convenient location, and a focus on sustainability.",
    text1:"Godrej Woods is a premium residential project located in Sector 43, Noida, offering luxurious 2, 3, and 4 BHK apartments with top-notch amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed with modern architecture and spacious interiors, providing a comfortable living experience. The project is strategically located with easy access to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Godrej Woods is a great choice for those looking for a premium living experience in Noida.",
    video:"https://www.youtube.com/watch?v=z0avNg3bDks",
    para1:"Godrej Woods is a luxurious residential project located in Sector 43, Noida, Uttar Pradesh. Developed by Godrej Properties, this project offers well-designed 2 BHK, 3 BHK, and 4 BHK apartments that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Godrej Woods are spacious and well-ventilated, with sizes ranging from 1350 square feet to 2650 square feet. The apartments are designed to provide maximum natural light and ventilation and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Godrej Woods also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 43, Noida, Godrej Woods enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Godrej Woods is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Godrej Woods is the perfect place to call home.",
  },
  { id:'HT4', 
    propertyname:"Trident Reso",
    img:publicUrl+"assets/img/banner/tridentembassy.webp",
    floorPlan1:publicUrl+"assets/img/FloorPlan/Trident/1.jpg",
    floorPlan2:publicUrl+"assets/img/FloorPlan/Trident/2.jpg",
    floorPlan3:publicUrl+"assets/img/FloorPlan/Trident/3.jpg",
    price:"73 Lakhs- 1.2 Cr ",
    address1:"Greater Noida West",
    address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
    RERANO:"UPRERAPRJ785019",
    status:"Under Construction",
    launchDate:"Jan 2021",
    projectType:"Residential",
    projectArea:"3.25 Acres",
    sizes:"1272 - 1922 Sq.ft.",
    launchDate:"Feb, 2021",
    possessionDate:"Dec, 2025",
    totalTowers:"5 Towers",
    totalFloors:"22 Floors",
    configurations:"2BHK, 3BHK, 4BHK ",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.0129681049725!2d77.43277193488767!3d28.56937330000001!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ceec4a05c4e9b%3A0x7696629e81633ef!2sTRIDENT%20EMBASSY%20RESO!5e0!3m2!1sen!2sin!4v1674031721198!5m2!1sen!2sin", 
    totalFlats:"572",
    greenArea:"70%",
    totalFloors:"22",
    ceilingHeight:"10 Ft.",
    mainDoorHeight:"9 Ft.",
    internalDoorHeight:"7 Ft.",
    para1:"Trident Embassy Reso is a premium residential project located in Sector 1, Greater Noida West. Developed by Trident Realty, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Trident Embassy Reso are well-designed and come in 2 BHK, 3 BHK, and 4 BHK configurations, with sizes ranging from 990 square feet to 2285 square feet. The apartments are spacious and well-ventilated and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Trident Embassy Reso also offers a wide range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 1, Greater Noida West, Trident Embassy Reso enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Trident Embassy Reso is a great investment for homebuyers looking for a luxurious and comfortable living experience in Greater Noida West. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Trident Embassy Reso is the perfect place to call home.",
    text1:"Trident Embassy Reso is a premium residential project located in Sector 1, Greater Noida West, offering luxurious 2, 3, and 4 BHK apartments with world-class amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed with modern architecture and spacious interiors, providing a comfortable and elegant living experience. The project is located in a prime location with easy access to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Trident Embassy Reso is an excellent choice for those looking for a premium living experience in Greater Noida West.",
  }
  ,{ id:'HT5', 
  propertyname:"Ace Startlit",
  img:publicUrl+"assets/img/banner/Star.jpg",
  floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
  floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
  floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
  price:"1 Cr- 1.4 Cr ",
  address1:"Sector 152, Noida",
  address2:"SC-01/09, Sector 152, Noida, Uttar Pradesh 201303",
  RERANO:"UPRERAPRJ677294",
  status:"Under Construction",
  projectType:"Residential",
  projectArea:"7 Acres",
  sizes:"1350 - 1775 Sq.ft.",
  projectUnits:"496 Flats",
  launchDate:"May 2021",
  possessionDate:"April 2025",
  totalTowers:"5 Towers",
  totalFloors:"G+16 Floors",
  projectStatus:"Under Construction",
  configurations:"2BHK, 3BHK",
  location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3508.052801603713!2d77.46963881829703!3d28.447824651381527!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cc1e91a98d78b%3A0xa19520e37654e5d5!2sACE%20Starlit!5e0!3m2!1sen!2sin!4v1679739244588!5m2!1sen!2sin", 
  totalFlats:"492",
  greenArea:"70%",
  parkingLevel:"25%",
  totalFloors:"28",
  ceilingHeight:"10 Ft.",
  mainDoorHeight:"9 Ft.",
  internalDoorHeight:"7 Ft.",
  para1:"Ace Starlit is a premium residential project located in Sector 152, Noida, Uttar Pradesh. Developed by Ace Group, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
  para2:"The apartments at Ace Starlit are well-designed and come in 2 BHK, 3 BHK, and 4 BHK configurations, with sizes ranging from 1085 square feet to 3220 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
  para3:"Ace Starlit also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
  para4:"Located in Sector 152, Noida, Ace Starlit enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
  para5:"Overall, Ace Starlit is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Ace Starlit is the perfect place to call home.",
  text1:"Ace Starlit is a premium residential project located in Sector 152, Noida, offering luxurious 2, 3, and 4 BHK apartments with world-class amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed with modern architecture and spacious interiors, providing a comfortable and elegant living experience. The project is located in a prime location with easy access to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Ace Starlit is an excellent choice for those looking for a premium living experience in Noida."

},
{ id:'HT6', 
propertyname:"Kalpataru Vista ",
img:publicUrl+"assets/img/banner/kalpataruvista.webp",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"3.4 Cr- 4.7 Cr ",
address1:"Sector 128 Noida",
address2:"Kalpataru Vista, Plot B 24 C Wish Town, Sector 128 Noida, Uttar Pradesh 201304",
RERANO:" UPRERAPRJ14980",
projectType:"Residential",
projectArea:"3 Acres",
sizes:"3011 - 4145 Sq.ft.",
launchDate:"May, 2018",
possessionDate:"April 2024",
totalTowers:"2",
totalFloors:"34 Floors",
status:"Under Construction",
configurations:"3BHK, 4BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3505.655759661275!2d77.35810201455693!3d28.520002995917014!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce7cfaa61f5b7%3A0xeee1789eb2eac629!2sKalpataru%20Vista!5e0!3m2!1sen!2sin!4v1679739330826!5m2!1sen!2sin" , 
totalFlats:"250 Flats",
greenArea:"78%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Kalpataru Vista is a luxurious residential project located in Sector 128, Noida, Uttar Pradesh. Developed by Kalpataru Group, this project offers premium living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Kalpataru Vista are well-designed and come in 3 BHK and 4 BHK configurations, with sizes ranging from 2007 square feet to 2763 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Kalpataru Vista also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 128, Noida, Kalpataru Vista enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Kalpataru Vista is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Kalpataru Vista is the perfect place to call home.",
text1:"Kalpataru Vista is a luxurious residential project located in Sector 128, Noida. The project offers premium 3 and 4 BHK apartments with contemporary design and world-class amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed to provide a comfortable and luxurious living experience with spacious interiors and elegant finishes. The project is located in a prime location with excellent connectivity to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Kalpataru Vista is an excellent choice for those looking for a premium living experience in Noida."

},
{ id:'HT7', 
propertyname:"Parx Laureate",
img:publicUrl+"assets/img/banner/parx.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Parx/1.jpg",
floorPlan2:publicUrl+"assets/img/FloorPlan/Parx/2.jpg",
floorPlan3:publicUrl+"assets/img/FloorPlan/Parx/3.jpg",
price:"3.3 Cr- 4.8 Cr ",
address1:"Sector 108, Noida",
address2:"H-01 Sector 108, Noida Expressway, Noida, 201304.",
RERANO:" UPRERAPRJ5998",
status:"Ready to Move",
launchDate:"March 2018",
possessionDate:"Ready to Move",
projectType:"Residential",
projectArea:"11 Acres",
sizes:"3302- 4874 Sq.ft.",
totalTowers:"9 Towers",
totalFloors:"21 Floors",
configurations:"3BHK, 4BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7011.020716489376!2d77.37025807334001!3d28.524375856372878!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce618d3158e8d%3A0x6b798b0b2bfa005b!2sParx%20Laureate%2C%20Sector%20108%2C%20Noida%2C%20Uttar%20Pradesh!5e0!3m2!1sen!2sin!4v1679739378623!5m2!1sen!2sin", 
totalFlats:"570 Flats",
greenArea:"78%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Parx Laureate is a premium residential project located in Sector 108, Noida, Uttar Pradesh. Developed by Laureate Buildwell Pvt. Ltd., this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Parx Laureate are well-designed and come in 3 BHK and 4 BHK configurations, with sizes ranging from 3195 square feet to 3800 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Parx Laureate also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 108, Noida, Parx Laureate enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Parx Laureate is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Parx Laureate is the perfect place to call home.",
text1:"Parx Laureate is a premium residential project located in Sector 108, Noida. The project offers luxurious 3 and 4 BHK apartments with contemporary design and world-class amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed to provide a comfortable and luxurious living experience with spacious interiors and elegant finishes. The project is located in a prime location with excellent connectivity to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Parx Laureate is an excellent choice for those looking for a premium living experience in Noida.",
video:"https://www.youtube.com/embed/CJoKqDDMEww"
},
{ id:'HT8', 
propertyname:"Tata Eureka",
img:publicUrl+"assets/img/banner/tataeureka.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Tataeureka/1.jpg",
floorPlan2:publicUrl+"assets/img/FloorPlan/Tataeureka/1.jpg",
floorPlan3:publicUrl+"assets/img/FloorPlan/Tataeureka/1.jpg",
price:"88 Lakhs- 1.26 Cr ",
address1:"Sector 150 Noida",
address2:"SC-01 A1, Sector 150, Noida, Uttar Pradesh 201310",
RERANO:"UPRERAPRJ469983",
status:"Under Construction",
launchDate:"May 2017",
projectType:"Residential",
projectArea:"20 Acres",
sizes:"1100 - 1575 Sq.ft.",
projectUnits:"1160 Flats",
possessionDate:"Sep, 2023",
totalTowers:"20 Towers",
totalFloors:"28 Floors",
configurations:"2BHK, 3BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1754.496229486344!2d77.48419290799964!3d28.419484404594524!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cc1fd2779cc97%3A0x13b2293706a249e3!2sTata%20Eureka%20Park!5e0!3m2!1sen!2sin!4v1679739473260!5m2!1sen!2sin", 
greenArea:"80%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Tata Eureka Park is a premium residential project located in Sector 150, Noida, Uttar Pradesh. Developed by Tata Value Homes, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
para2:"The apartments at Tata Eureka Park are well-designed and come in 2 BHK and 3 BHK configurations, with sizes ranging from 1100 square feet to 1575 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
para3:"Tata Eureka Park also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
para4:"Located in Sector 150, Noida, Tata Eureka Park enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
para5:"Overall, Tata Eureka Park is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Tata Eureka Park is the perfect place to call home.",
text1:"Tata Eureka Park is a premium residential project located in Sector 150, Noida. Spread across 20 acres, the project offers 2 and 3 BHK apartments in high-rise towers with contemporary design and world-class amenities. The apartments are designed to provide a comfortable and luxurious living experience with spacious interiors and elegant finishes. The project also incorporates several green features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. The project is located in a prime location with excellent connectivity to major landmarks and is well-connected to other parts of the city via major highways and roads. With its prime location, luxurious amenities, and sustainable features, Tata Eureka Park is an excellent choice for those looking for a premium living experience in Noida."

},
{ id:'HT9', 
propertyname:"County 107",
img:publicUrl+"assets/img/banner/county.webp",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"4.9 Cr - 9.19 Cr ",
address1:"Sector 107, Noida",
address2:"GH 01A, B ALPHA, Sector 107, Noida, Uttar Pradesh 201301",
RERANO:"UPRERAPRJ837374",
status:"Under Construction",
launchDate:"Dec 2019",
projectArea:"5 Acres",
totalFlats:"224 Flats",
sizes:"3501- 6570 Sq.ft.",
projectUnits:"245 Flats",
possessionDate:"Dec, 2023",
totalTowers:"4 Towers",
totalFloors:"31 Floors",
propertyType:"Residential",
configurations:"4BHK, 5BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.7486617908994!2d77.37307671455761!3d28.547273394686542!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce555ac338307%3A0x7a7d098909002d22!2sCounty%20107!5e0!3m2!1sen!2sin!4v1679740437344!5m2!1sen!2sin",
greenArea:"78%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"County 107 is a premium residential project located in Sector 107, Noida, Uttar Pradesh. Developed by ABA Corp, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at County 107 are well-designed and come in 3 BHK and 4 BHK configurations, with sizes ranging from 1895 square feet to 2720 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"County 107 also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 107, Noida, County 107 enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, County 107 is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, County 107 is the perfect place to call home.",
text1:"County 107 is a luxurious residential project located in Sector 107, Noida. The project offers 3 and 4 BHK apartments with premium amenities and elegant design. The apartments are designed to provide a comfortable and luxurious living experience with spacious interiors and modern finishes. The project also incorporates several lifestyle amenities like a clubhouse, swimming pool, gymnasium, and more, making it an ideal choice for those who enjoy an active lifestyle. The project is located in a prime location with excellent connectivity to major landmarks and is well-connected to other parts of the city via major highways and roads. With its prime location, luxurious amenities, and elegant design, County 107 is an excellent choice for those looking for a premium living experience in Noida."

},
{ id:'HT10', 
propertyname:"Eldeco Live By The Greens",
img:publicUrl+"assets/img/banner/Eldeco.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Eldeco/1.jpg",
floorPlan2:publicUrl+"assets/img/FloorPlan/Eldeco/2.jpg",
floorPlan3:publicUrl+"assets/img/FloorPlan/Eldeco/3.jpg",
price:"85 Lakhs - 1 Cr ",
address1:"Sector 150, Noida",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ15172",
status:"Under Construction",
launchDate:"May 2017",
projectType:"Residential",
projectArea:"20 Acres",
sizes:"1137 - 1404 Sq.ft.",
launchDate:"Feb, 2018",
possessionDate:"Dec 2023",
totalTowers:"17 Towers",
totalFloors:"G + 22 Floors",
configurations:"2BHK, 3BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3509.034572277574!2d77.4832939182916!3d28.418213652745607!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cc175e7bce8df%3A0xa38445461590a6!2sEldeco%20Live%20by%20the%20Greens!5e0!3m2!1sen!2sin!4v1679740492839!5m2!1sen!2sin" , 
totalFlats:"1700 Flats",
greenArea:"80%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Eldeco Live by the Greens is a premium residential project located in Sector 150, Noida, Uttar Pradesh. Developed by Eldeco Group, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Eldeco Live by the Greens are well-designed and come in 2 BHK, 3 BHK and 4 BHK configurations, with sizes ranging from 1137 square feet to 2025 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Eldeco Live by the Greens also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 150, Noida, Eldeco Live by the Greens enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Eldeco Live by the Greens is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Eldeco Live by the Greens is the perfect place to call home.",
text1:"Eldeco Live By The Greens is a premium residential project located in Sector 150, Noida. Spread across a vast area of lush greenery, the project offers luxurious 2, 3, and 4 BHK apartments that are designed to offer a comfortable and modern living experience. The apartments are spacious and well-ventilated, with large windows that allow natural light and fresh air to enter. The project also offers a wide range of amenities including a swimming pool, a fully equipped gymnasium, a jogging track, a clubhouse, a kids' play area, and more. With its strategic location, top-notch amenities, and exquisite design, Eldeco Live By The Greens is an ideal destination for those seeking a premium lifestyle in Noida."

},
{ id:'HT11', 
propertyname:"Purvanchal Royal City",
img:publicUrl+"assets/img/banner/purvanchal.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Purvanchal/1.jpg",
floorPlan2:publicUrl+"assets/img/FloorPlan/Purvanchal/2.jpg",
floorPlan3:publicUrl+"assets/img/FloorPlan/Purvanchal/3.jpg",
price:"1 Cr - 1.25 Cr ",
address1:"Greater Noida West",
address2:"Plot No GH 05B, Sector 1, Noida Extension, Greater Noida West, UP",
RERANO:"UPRERAPRJ3137",
status:"Ready to Move",
launchDate:"May 2017",
possessionDate:"Ready to Move",
projectType:"Residential",
projectArea:"22 Acres",
sizes:"1725-4700 Sq.Ft.",
launchDate:"Jan, 2019",
possessionDate:"Sep, 2023",
totalTowers:"17",
totalFloors:"19",
configurations:"3 BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3508.6307493996155!2d77.50384631455489!3d28.430396699952638!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cc174c16fd017%3A0x1a4677eabd34b0bc!2sPurvanchal%20Royal%20City!5e0!3m2!1sen!2sin!4v1679740669055!5m2!1sen!2sin" , 
totalFlats:"1240",
greenArea:"80%",
ceilingHeight:"10 Ft",
mainDoorHeight:"9 Ft",
internalDoorHeight:"7 Ft",
para1:"Purvanchal Royal City is a premium residential project located in Sector 137, Noida, Uttar Pradesh. Developed by Purvanchal Group, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Purvanchal Royal City are well-designed and come in 3 BHK and 4 BHK configurations, with sizes ranging from 1725 square feet to 3210 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Purvanchal Royal City also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 137, Noida, Purvanchal Royal City enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Purvanchal Royal City is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Purvanchal Royal City is the perfect place to call home.",
text1:"Purvanchal Royal City is a luxurious residential complex located in Sector CHI V of Greater Noida. The project offers a range of 3 and 4 BHK apartments that are built with the highest standards of quality and design. The apartments are spacious and well-ventilated, providing a comfortable and luxurious living experience. The project is spread over 22 acres of land and offers a wide range of amenities, including a clubhouse, swimming pool, gymnasium, and landscaped gardens. The project is strategically located, with easy access to major highways and metro stations, making it an ideal choice for those looking for a comfortable and convenient lifestyle. The project is built by Purvanchal Group, a well-known real estate developer with a reputation for delivering high-quality projects on time.",
video:"https://www.youtube.com/embed/Mr6lWeAO2y8"
},
{ id:'HT12', 
propertyname:"Dasnac Burj Noida",
img:publicUrl+"assets/img/banner/burj.webp",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"2.89 Cr - 7.25 Cr ",
address1:"Sector 75, Noida",
address2:"Sector 75, Noida",
RERANO:"UPRERAPRJ498423",
status:"Under Construction",
launchDate:"April 2019",
possessionDate:"Ready to Move",
projectType:"Residential",
projectArea:"1 Acres",
sizes:"2510.00 sq.ft. - 6300.00 sq.ft.",
projectUnits:"131 units",
possessionDate:"Dec, 2023",
totalTowers:"1",
configurations:"3, 4, 5.5 BHK Apartment, Duplexes",
location:"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14015.233447054106!2d77.3819281!3d28.5755168!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef0bb7b93bd9%3A0x723ac9083147a601!2sDASNAC%20Burj%20Noida%20(Official)!5e0!3m2!1sen!2sin!4v1679295825659!5m2!1sen!2sin", 
totalFlats:"131",
greenArea:"80%",
totalFloors:"35",
ceilingHeight:"10 ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Dasnac Burj Noida is a luxurious residential project located in Sector 75, Noida, Uttar Pradesh. Developed by Dasnac Design Arch, this project offers spacious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Dasnac Burj Noida come in 3 BHK and 4 BHK configurations, with sizes ranging from 1950 square feet to 3950 square feet. The apartments are well-designed and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Dasnac Burj Noida also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 75, Noida, Dasnac Burj Noida enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Dasnac Burj Noida is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Dasnac Burj Noida is the perfect place to call home.",
text1:"Dasnac Burj Noida is a luxurious residential project located in the prime location of Sector 75, Noida. The project offers a wide range of spacious and beautifully designed apartments that are equipped with modern amenities to provide a comfortable lifestyle. The apartments are available in 3BHK and 4BHK configurations with sizes ranging from 1950 sq. ft. to 3450 sq. ft. The project boasts of world-class amenities such as a state-of-the-art clubhouse, swimming pool, landscaped gardens, children's play area, gymnasium, and many more. The project is strategically located with easy access to major highways and is in close proximity to reputed educational institutions, hospitals, shopping centers, and entertainment hubs, making it an ideal place to call home. With its luxurious amenities, prime location, and exquisite design, Dasnac Burj Noida is a perfect place for those looking to enjoy a sophisticated and comfortable lifestyle.",
video:"https://www.youtube.com/embed/tvSpvquWZ8E"
},
{ id:'HT13', 
propertyname:"Gulshan Dynasty",
img:publicUrl+"assets/img/banner/gulshandynasty.webp",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"7.5 Cr ",
address1:"Sector 144",
address2:"Sector 144, Noida-Greater Noida Expressway, Noida",
RERANO:"UPRERAPRJ950870",
PropertyID:"HZ29",
status:"Ready to Move",
launchDate:"May 2017",
possessionDate:"Ready to Move",
projectType:"Residential",
projectArea:"5.8 Acres",
totalTowers:"1",
sizes:"4700.00 sq.ft.",
projectUnits:"204 units",
launchDate:"Nov, 2019",
possessionDate:"Nov, 2024",
configurations:"4 BHK Apartment",
location:"https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14025.547583075506!2d77.4395886!3d28.4980052!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce9293106346f%3A0xcfd1e8b39fc76e0f!2sGulshan%20Dynasty!5e0!3m2!1sen!2sin!4v1679302667536!5m2!1sen!2sin", 
totalFlats:"204 units",
greenArea:"80%",
totalFloors:"32",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
text:"Gulshan Dynasty is a luxury residential project located in the heart of Noida. The project offers spacious and well-designed apartments in various configurations ranging from 3 BHK to 4 BHK. The apartments are equipped with modern amenities and facilities such as a clubhouse, swimming pool, gymnasium, kids play area, landscaped gardens, and more. The project is strategically located with excellent connectivity to major highways, metro stations, and other essential conveniences like schools, hospitals, and shopping centers. Gulshan Dynasty is designed to provide a luxurious lifestyle with world-class amenities and features. The project is also designed to offer a sustainable living experience with eco-friendly practices like rainwater harvesting, waste management, and more. The project is developed by Gulshan Homz, a reputed real estate developer known for its quality and timely delivery. With Gulshan Dynasty, residents can enjoy a luxurious and comfortable lifestyle in the heart of Noida.",
text1:"Gulshan Dynasty is a premium residential project located in Sector 144, Noida. The project offers 2, 3, and 4 BHK apartments ranging from 1,315 square feet to 2,795 square feet. The apartments are designed with modern architecture and are well-ventilated, spacious, and equipped with all necessary amenities. The project is spread across a vast expanse of land and offers lush green surroundings, ensuring a comfortable and healthy lifestyle for residents. Some of the amenities available in Gulshan Dynasty include a swimming pool, gymnasium, landscaped garden, clubhouse, and kids play area, among others. The location of Gulshan Dynasty is also a major advantage as it is well-connected to major highways and offers easy access to schools, hospitals, and commercial areas. Overall, Gulshan Dynasty offers a luxurious and comfortable living experience for those looking to invest in a premium residential project in Noida.",
para1:"Gulshan Dynasty is a premium residential project located in Sector 144, Noida, Uttar Pradesh. Developed by Gulshan Homz, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
para2:"The apartments at Gulshan Dynasty are well-designed and come in 3 BHK and 4 BHK configurations, with sizes ranging from 1500 square feet to 2400 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
para3:"Gulshan Dynasty also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
para4:"Located in Sector 144, Noida, Gulshan Dynasty enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
para5:"Overall, Gulshan Dynasty is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Gulshan Dynasty is the perfect place to call home.",

},
{ id:'HT14', 
propertyname:"Godrej Nest",
img:publicUrl+"assets/img/banner/Nest.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"1.46 Cr - 2.39 Cr ",
address1:"Sector 150",
address2:"Sector 150, Noida-Greater Noida Expressway, Noida",
RERANO:"UPRERAPRJ13521",
PropertyID:"HZ29",
status:"Under Construction",
launchDate:"Nov, 2017",
possessionDate:"Mar, 2025",
projectType:"Residential",
projectArea:"18 Acres",
sizes:"1907.00 sq.ft. - 3027.00 sq.ft.",
launchDate:"Nov, 2017",
possessionDate:"Mar, 2025",
totalTowers:"14",
totalFloors:"31",
configurations:"3, 4 BHK Apartments",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3508.961647329656!2d77.49184201455466!3d28.420414100401555!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cc17b07d6cb7f%3A0xe77057bdd6c21349!2sGodrej%20Nest%2C%20Noida!5e0!3m2!1sen!2sin!4v1679740775899!5m2!1sen!2sin" , 
totalFlats:"1200",
greenArea:"70%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft.",
internalDoorHeight:"7 Ft.",
para1:"Godrej Nest is a luxurious residential project located in Sector 150, Noida, Uttar Pradesh. Developed by Godrej Properties, this project offers spacious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Godrej Nest come in 2 BHK, 3 BHK, and 4 BHK configurations, with sizes ranging from 1250 square feet to 3050 square feet. The apartments are well-designed and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Godrej Nest also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 150, Noida, Godrej Nest enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Godrej Nest is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Godrej Nest is the perfect place to call home.",
text1:"Godrej Nest is a luxurious residential project located in the prime location of Sector 150 in Noida. Spread across 9 acres of land, it offers a perfect blend of comfortable living and contemporary architecture. The project comprises of 7 towers and 926 units of 1 BHK, 2 BHK, 3 BHK, and 4 BHK apartments with sizes ranging from 712 square feet to 2,347 square feet. The apartments are equipped with modern amenities like a fully equipped gymnasium, clubhouse, swimming pool, kids' play area, landscaped garden, 24/7 security and surveillance, and more. The location of Godrej Nest is another major advantage, as it is well-connected to various parts of Noida, Greater Noida, and Delhi NCR. With its luxurious features, modern amenities, and prime location, Godrej Nest is an ideal destination for those seeking a perfect blend of luxury, comfort, and convenience."

},
{ id:'HT15', 
propertyname:"Ivy County",
img:publicUrl+"assets/img/banner/ivycounty.jpg",
floorPlan1:publicUrl+"assets/img/FloorPlan/Acedivino/1.png",
floorPlan2:publicUrl+"assets/img/FloorPlan/Acedivino/2.png",
floorPlan3:publicUrl+"assets/img/FloorPlan/Acedivino/3.png",
price:"1.49 Cr - 2.26 Cr",
address1:"Sector 75",
address2:"Sector 75",
RERANO:"UPRERAPRJ757529",
status:"Under Construction",
launchDate:"May 2017",
projectType:"Residential",
projectArea:"5 Acres",
sizes:"1656-2511 Sq.Ft.",
possessionDate:"Sep 23",
totalTowers:"5",
totalFloors:"27",
configurations:"3 BHK,4 BHK",
location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.7794870494117!2d77.38371981455833!3d28.57638369337195!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390cef1b8a9d800f%3A0x23a44f04ca87dec3!2sIVY%20County!5e0!3m2!1sen!2sin!4v1679740834376!5m2!1sen!2sin" ,
totalFlats:"546",
greenArea:"78%",
ceilingHeight:"10 Ft.",
mainDoorHeight:"9 Ft",
internalDoorHeight:"7 Ft.",
para1:"Ivy County is a premium residential project located in Sector 75, Noida, Uttar Pradesh. Developed by ABA Corp, this project offers luxurious and comfortable living spaces that cater to the needs and preferences of modern-day families.",
    para2:"The apartments at Ivy County are well-designed and come in 2 BHK, 3 BHK, and 4 BHK configurations, with sizes ranging from 1195 square feet to 2595 square feet. The apartments are spacious and well-ventilated, and come equipped with a range of modern amenities and facilities, including air conditioning, modular kitchens, high-speed elevators, and 24/7 security services.",
    para3:"Ivy County also offers a range of recreational and lifestyle facilities, including a swimming pool, a gymnasium, a club house, a children's play area, and a dedicated sports area. The project also features beautifully landscaped gardens and green spaces that provide a serene and peaceful environment for residents to relax and unwind.",
    para4:"Located in Sector 75, Noida, Ivy County enjoys excellent connectivity to major business and commercial hubs in Noida and Delhi. The project is well-connected to major roads and highways, including the Noida-Greater Noida Expressway, the Yamuna Expressway, and the FNG Expressway. It is also located close to major metro stations and bus stops, making it easy for residents to commute to different parts of the city.",
    para5:"Overall, Ivy County is a great investment for homebuyers looking for a luxurious and comfortable living experience in the bustling city of Noida. With its range of modern amenities and facilities, excellent connectivity, and serene environment, Ivy County is the perfect place to call home.",
text1:"Ivy County Noida is a premium residential complex located in one of the most sought-after areas of Noida. The complex offers a luxurious living experience with modern amenities and state-of-the-art architecture. It is designed to cater to the needs and preferences of modern families, providing spacious and well-designed apartments with premium finishes and fittings.Residents of Ivy County Noida can enjoy a range of modern amenities, including a swimming pool, gymnasium, landscaped gardens, clubhouse, and sports facilities. It is a great opportunity to invest in the growing real estate market of Noida and secure a premium property in a prime location.Overall, Ivy County Noida is a premium residential complex that offers a modern and luxurious living experience in the heart of Noida. Its modern amenities, prime location, and investment potential make it an ideal choice for those looking for a comfortable and convenient living space or a smart investment opportunity. "

}
  ];

