

export const data =[
    { id:'HT2', 
    propertyname:"Ambience Tiverton ",
    img:"https://i.ibb.co/JthY4Zf/Ambience-Tirevton-01.webp",
    address1:"Sector 50, Noida",
    address2:"F-33, F Block, Sector 50, Noida",
    price:"10,600",
    RERANO:"UPRERAPRJ4249",
    PropertyID:"HZ29",
    LaunchDate:"October 2014",
    projectarea:"4 Acres",
    Sizes:"2548 - 6055 Sq.ft.",
    PossessionDate:"March, 2020",
    TotalTowers:"7 Towers",
    TotalFloors:"26 Floors",
    ProjectStatus:"Ready To Move",
    PropertyType:"Residential",
    Configurations:"3 BHK, 4 BHK ,5 BHK",
    location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3503.7506412924913!2d77.36810131549448!3d28.577249693330682!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5b84c2b5a73%3A0xaf840e835cff6c27!2sAmbience%20Tiverton!5e0!3m2!1sen!2sin!4v1674031553468!5m2!1sen!2sin" ,
    ConstructionType: "",
    TotalFlats:"284",
    GreenArea:"70%",
    TotalFloors:"25",
    Ceilingheight:"10 Ft.",
    MainDoorHeight:"9 Ft.",
    InternalDoorHeight:"7 Ft.",
    text:"Ambience Tiverton is a luxury residential project located in Sector 50, Noida, India. The project is developed by Ambience Group, a renowned real estate developer known for its premium projects across India. Ambience Tiverton offers spacious apartments with modern amenities and facilities, making it an ideal choice for those looking for a comfortable and luxurious living experience.Features and Amenities:Ambience Tiverton offers 3-4 BHK apartments with spacious balconies, allowing residents to enjoy the panoramic views of the surroundings. The apartments are designed to provide maximum comfort and convenience to the residents. The project is equipped with a range of amenities and facilities such as a clubhouse, swimming pool, gym, sports facilities, and landscaped gardens. The project also features a multi-level car parking facility, 24x7 security, and power backup.Location and Connectivity:Ambience Tiverton is located in Sector 50, Noida, which is a prime residential area in the city. The location is well-connected to other parts of Noida, as well as Delhi and other NCR cities, via roads, highways, and metro. The project is in close proximity to major IT hubs and commercial centers, making it an ideal choice for working professionals.Design and Architecture:Ambience Tiverton boasts of a contemporary and elegant design, with modern architecture and interiors. The apartments are designed to maximize natural light and ventilation, providing a healthy living environment for the residents. The project has received several awards and recognitions for its design, architecture, and construction quality.Investment Potential:Ambience Tiverton is a premium residential project that offers a high-end living experience. The project is designed to cater to the needs of the urban elite, and the apartments are priced accordingly. The location of the project, along with the premium amenities and facilities, makes it a desirable investment option for those looking for a luxurious and comfortable living experience.In conclusion, Ambience Tiverton is a premium residential project that offers a luxurious living experience. With its modern amenities, prime location, and contemporary design, the project is an ideal choice for those looking for a comfortable and luxurious lifestyle.",
    text1:"Ambience Tiverton is a luxurious residential project located in Sector 50, Noida. It offers spacious 3 and 4 BHK apartments with modern amenities such as a swimming pool, gymnasium, clubhouse, and landscaped gardens. The apartments are equipped with state-of-the-art facilities such as modular kitchens with granite counters, imported marble flooring in living, dining, and bedrooms, and high-quality bathroom fittings. The project is conveniently located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. With its luxurious amenities and convenient location, Ambience Tiverton offers a comfortable living experience for those seeking a premium lifestyle in Noida."
  },
  { id:'HT3', 
  propertyname:"Godrej Woods",
  img:"https://i.ibb.co/qY1CJZc/Godrej-Wood-01.webp",
  price:"11,590 ",
  address1:"Sector 43, Noida",
  address2:"Block A, Sector 43, Noida, Uttar Pradesh 201303",
  RERANO:"UPRERAPRJ704730",
  status:"Ready to Move",
  LaunchDate:"May 2017",
  PossessionDate:"Ready to Move",
  Projecttype:"Residential",
  projectarea:"11 Acres",
  Sizes:"1255 - 3759 Sq.ft.",
  ProjectUnits:"1100 Flats",
  LaunchDate:"Jan, 2021",
  TotalTowers:"10 Towers",
  TotalFloors:"34 Floors",
  Configurations:"2BHK, 3BHK, 4BHK, 5BHK",
  location:"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3504.3666738551206!2d77.34894121549411!3d28.558750094166488!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390ce5d5046eee85%3A0x9ed7749be19b1b56!2sGodrej%20Woods%2C%20Sector%2043%2C%20Noida!5e0!3m2!1sen!2sin!4v1674031636046!5m2!1sen!2sin",   
  TotalFlats:"1245",
  GreenArea:"70%",
  TotalFloors:"34",
  Ceilingheight:"10 Ft",
  MainDoorHeight:"9 Ft.",
  InternalDoorHeight:"7 Ft.",
  text:"Godrej Woods is a residential project by Godrej Properties located in Sector 43, Noida. The project offers luxurious 2, 3, and 4 BHK apartments with world-class amenities such as a clubhouse, swimming pool, gymnasium, children's play area, and landscaped gardens. The apartments are spacious and well-designed, offering residents a comfortable living experience. The project also features 24/7 security and surveillance systems, ensuring the safety of residents.Godrej Woods is strategically located and offers easy access to major landmarks such as schools, hospitals, shopping centers, and entertainment zones. The project is also well-connected to other parts of the city via major highways and roads, making it an ideal choice for those who need to commute regularly.The project is built with a focus on sustainability and environmental responsibility, with features such as rainwater harvesting, solar power generation, and waste management systems. This makes it a great choice for those who are conscious about the environment and want to contribute to a greener future.Overall, Godrej Woods is a great choice for those seeking a luxurious and comfortable living experience in Noida, with world-class amenities, convenient location, and a focus on sustainability.",
  text1:"Godrej Woods is a premium residential project located in Sector 43, Noida, offering luxurious 2, 3, and 4 BHK apartments with top-notch amenities such as a clubhouse, swimming pool, gymnasium, and landscaped gardens. The apartments are designed with modern architecture and spacious interiors, providing a comfortable living experience. The project is strategically located with easy access to major landmarks and is well-connected to other parts of the city via major highways and roads. It also incorporates sustainable features like rainwater harvesting, solar power generation, and waste management systems, making it an ideal choice for those who are environmentally conscious. With its prime location, luxurious amenities, and sustainable features, Godrej Woods is a great choice for those looking for a premium living experience in Noida."
  
  },
  
      ];
    
    